apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # kube-state-metrics (upstream v2.13.0, deploys into kube-system)
  - kube-state-metrics/cluster-role.yaml
  - kube-state-metrics/cluster-role-binding.yaml
  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/service.yaml
  - kube-state-metrics/service-account.yaml
  # Node exporter
  - node-exporter/daemonset.yaml
  - node-exporter/service.yaml
  # Prometheus
  - prometheus/serviceaccount.yaml
  - prometheus/clusterrole.yaml
  - prometheus/clusterrolebinding.yaml
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - prometheus/ingress.yaml
  # Grafana
  - grafana/deployment.yaml
  - grafana/service.yaml
  - grafana/ingress.yaml
  - grafana/configmap-datasources.yaml
  - grafana/configmap-dashboards.yaml
